name       : gexiv2
version    : 0.10.8
release    : 8
source     :
    - https://download.gnome.org/sources/gexiv2/0.10/gexiv2-0.10.8.tar.xz : 81c528fd1e5e03577acd80fb77798223945f043fd1d4e06920c71202eea90801
license    : GPL-2.0
component  : desktop.library
summary    : GObject wrapper around libexiv2
description: |
    gexiv2 is a GObject wrapper around the Exiv2 photo metadata library. It allows for GNOME applications to easily inspect and update EXIF, IPTC, and XMP metadata in photo and video files of various formats.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %configure --disable-static --enable-introspection
build      : |
    %make
install    : |
    %make_install
