name       : gexiv2
version    : 0.10.5
release    : 5
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gexiv2/0.10/gexiv2-0.10.5.tar.xz : 318fe068cd414c0af91759a87c29fd577cd5d42bf7a6f50caff27535c02ac7f3
license    : GPL-2.0
component  : desktop.library
summary    : GObject wrapper around libexiv2
description: |
    gexiv2 is a GObject wrapper around the Exiv2 photo metadata library. It allows for GNOME applications to easily inspect and update EXIF, IPTC, and XMP metadata in photo and video files of various formats.
builddeps  :
    - pkgconfig(exiv2)
setup      : |
    %configure --disable-static --enable-introspection
build      : |
    %make
install    : |
    %make_install
