name       : gexiv2
version    : 0.12.0
release    : 10
source     :
    - https://download.gnome.org/sources/gexiv2/0.12/gexiv2-0.12.0.tar.xz : 58f539b0386f36300b76f3afea3a508de4914b27e78f58ee4d142486a42f926a
license    : GPL-2.0-only
component  : desktop.library
summary    : GObject wrapper around libexiv2
description: |
    gexiv2 is a GObject wrapper around the Exiv2 photo metadata library. It allows for GNOME applications to easily inspect and update EXIF, IPTC, and XMP metadata in photo and video files of various formats.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
