name       : gexiv2
version    : 0.10.3
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gexiv2/0.10/gexiv2-0.10.3.tar.xz : 390cfb966197fa9f3f32200bc578d7c7f3560358c235e6419657206a362d3988
license    : GPL-2.0
summary    : GObject wrapper around libexiv2
description: |
    gexiv2 is a GObject wrapper around the Exiv2 photo metadata library. It allows for GNOME applications to easily inspect and update EXIF, IPTC, and XMP metadata in photo and video files of various formats.
builddeps  :
    - pkgconfig(exiv2)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
