name       : gexiv2
version    : 0.10.9
release    : 9
source     :
    - https://download.gnome.org/sources/gexiv2/0.10/gexiv2-0.10.9.tar.xz : 8806234aa6fd1c345d46bf07a14e82771415071ca5ff63615b1ea62bd2fec0ed
license    : GPL-2.0-only
component  : desktop.library
summary    : GObject wrapper around libexiv2
description: |
    gexiv2 is a GObject wrapper around the Exiv2 photo metadata library. It allows for GNOME applications to easily inspect and update EXIF, IPTC, and XMP metadata in photo and video files of various formats.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
